<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-7CF6N7D" name="com.srm.PRACTICE.PracticeTestNG" tests="7" failures="0" timestamp="28 Feb 2022 10:11:51 GMT" time="0.095" errors="1">
  <testcase name="Dataproviderpractice" time="0.000" classname="com.srm.PRACTICE.PracticeTestNG"/>
  <testcase name="contact" time="0.016" classname="com.srm.PRACTICE.PracticeTestNG"/>
  <testcase name="modification" time="0.000" classname="com.srm.PRACTICE.PracticeTestNG"/>
  <testcase name="Dataproviderpractice" time="0.000" classname="com.srm.PRACTICE.PracticeTestNG"/>
  <testcase name="Dataproviderpractice" time="0.016" classname="com.srm.PRACTICE.PracticeTestNG"/>
  <testcase name="Dataproviderpractice" time="0.063" classname="com.srm.PRACTICE.PracticeTestNG">
    <error type="org.testng.internal.reflect.MethodMatcherException" message="
Data provider mismatch
Method: Dataproviderpractice([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=int, declaredAnnotations=[]}])
Arguments: [null,null,null]">
      <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: Dataproviderpractice([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=int, declaredAnnotations=[]}])
Arguments: [null,null,null]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:983)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- Dataproviderpractice -->
  <testcase name="deleated" time="0.000" classname="com.srm.PRACTICE.PracticeTestNG"/>
</testsuite> <!-- com.srm.PRACTICE.PracticeTestNG -->
